export const SIGNUP_EMAIL_PASSWORD_REQUEST = 'SIGNUP_EMAIL_PASSWORD_REQUEST';
export const SIGNIN_EMAIL_PASSWORD_REQUEST = 'SIGNIN_EMAIL_PASSWORD_REQUEST';
export const SIGNIN_EMAIL_PASSWORD_SUCCESS = 'SIGNIN_EMAIL_PASSWORD_SUCCESS';
export const SIGNIN_EMAIL_PASSWORD_FAIL = 'SIGNIN_EMAIL_PASSWORD_FAIL';
// SIGNIN_EMAIL_PASSWORD_REQUEST_SUCCESS
export const SIGNUP_EMAIL_PASSWORD_SUCCESS = 'SIGNUP_EMAIL_PASSWORD_SUCCESS';
export const SIGNUP_EMAIL_PASSWORD_FAIL = 'SIGNUP_EMAIL_PASSWORD_FAIL';
export const FACEBOOK_SIGNUP_REQUEST = "FACEBOOK_SIGNUP_REQUEST"
export const FACEBOOK_SIGNUP_REQUEST_SUCCESS = "FACEBOOK_SIGNUP_REQUEST_SUCCESS"
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILUIER = 'ADD_POST_FAILUIER'
export const GOOGLE_SIGNUP_REQUEST = 'GOOGLE_SIGNUP_REQUEST'
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS'
export const TWITTER_SIGNUP_REQUEST = 'TWITTER_SIGNUP_REQUEST'
export const TWITTER_SIGNUP_SUCCESS = 'TWITTER_SIGNUP_SUCCESS'
export const PHONE_SIGNUP_REQUEST = 'PHONE_SIGNUP_REQUEST'
export const PHONE_SIGNUP_SUCCESS = 'PHONE_SIGNUP_SUCCESS'
export const LOGOUT = 'LOGOUT'




// add products constants..

export const ADD_PRODUCT_IDENTITY_REQUEST = 'ADD_PRODUCT_IDENTITY_REQUEST';
export const ADD_PRODUCT_IDENTITY_SUCCESS = 'ADD_PRODUCT_IDENTITY_SUCCESS';
export const ADD_PRODUCT_DESCRIPTION = 'ADD_PRODUCT_DESCRIPTION'
export const ADD_PRODUCT_DESCRIPTION_SUCCESS = 'ADD_PRODUCT_DESCRIPTION_SUCCESS'
export const ADD_PRODUCT_OPTIONS_AND_PRICES = 'ADD_PRODUCT_OPTIONS_AND_PRICES'
export const ADD_PRODUCT_FILE_UPLOADS = 'ADD_PRODUCT_FILE_UPLOADS'
export const ADD_PRODUCT_OPTIONS_AND_PRICES_SUCCESS = 'ADD_PRODUCT_OPTIONS_AND_PRICES_SUCCESS'
export const ADD_PRODUCT_FILE_OVERVIEW = 'ADD_PRODUCT_FILE_OVERVIEW'
export const ADD_PRODUCT_NEXT_TAB ='ADD_PRODUCT_NEXT_TAB'
export const GO_TO_TAB_STEP= 'GO_TO_TAB_STEP'
// sharl
export const ADD_ROW = "ADD_ROW"
export const ADD_MATERIAL = "ADD_MATERIAL"
export const ADD_SIZE = "ADD_SIZE"
export const ADD_INIT_PRICE = "ADD_INIT_PRICE"
export const ADD_OFFER_PRICE = "ADD_OFFER_PRICE"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const DELETE_ROW = "DELETE_ROW"
export const ADD_PRODUCT_PICTURES = "ADD_PRODUCT_PICTURES"
export const OPTIONS_STORED ="OPTIONS_STORED"