export const ENDPOINT = 'https://arch17-apis.herokuapp.com/api/'
// export const ENDPOINT = 'http://locahost:8000/api/'
export const SIGNUP_EMAIL_PASSWORD_REQUEST = 'SIGNUP_EMAIL_PASSWORD_REQUEST';
export const SIGNIN_EMAIL_PASSWORD_REQUEST = 'SIGNIN_EMAIL_PASSWORD_REQUEST';
export const NORMAL_SIGNUP_REQUEST = 'NORMAL_SIGNUP_REQUEST'
export const NORMAL_SIGNIN_REQUEST = 'NORMAL_SIGNIN_REQUEST'
export const SIGNIN_EMAIL_PASSWORD_SUCCESS = 'SIGNIN_EMAIL_PASSWORD_SUCCESS';
export const SIGNIN_EMAIL_PASSWORD_FAIL = 'SIGNIN_EMAIL_PASSWORD_FAIL';
export const SET_NAV_INFO = 'SET_NAV_INFO'
// export const CREATE_BRAND_NEXT = 'CREATE_BRAND_NEXT'
export const CREATE_BRAND_VERIFY_NEXT = 'CREATE_BRAND_VERIFY_NEXT'
export const CREATE_BRAND_BRAND_NEXT = 'CREATE_BRAND_BRAND_NEXT'
// SIGNIN_EMAIL_PASSWORD_REQUEST_SUCCESS
export const SIGNUP_EMAIL_PASSWORD_SUCCESS = 'SIGNUP_EMAIL_PASSWORD_SUCCESS';
export const SIGNUP_EMAIL_PASSWORD_FAIL = 'SIGNUP_EMAIL_PASSWORD_FAIL';
export const VANILLA_SIGNIN_EMAIL_PASSWORD_SUCCESS = 'VANILLA_SIGNIN_EMAIL_PASSWORD_SUCCESS'
export const FACEBOOK_SIGNUP_REQUEST = "FACEBOOK_SIGNUP_REQUEST"
export const FACEBOOK_SIGNUP_REQUEST_SUCCESS = "FACEBOOK_SIGNUP_REQUEST_SUCCESS"
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILUIER = 'ADD_POST_FAILUIER'
export const GOOGLE_SIGNUP_REQUEST = 'GOOGLE_SIGNUP_REQUEST'
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS'
export const POHONE_SIGNUP_REQUEST = 'POHONE_SIGNUP_REQUEST'
export const POHONE_SIGNUP_SUCCESS = 'POHONE_SIGNUP_SUCCESS'
export const TWITTER_SIGNUP_REQUEST = 'TWITTER_SIGNUP_REQUEST'
export const TWITTER_SIGNUP_SUCCESS = 'TWITTER_SIGNUP_SUCCESS'
export const PHONE_SIGNUP_REQUEST = 'PHONE_SIGNUP_REQUEST'
export const PHONE_SIGNUP_SUCCESS = 'PHONE_SIGNUP_SUCCESS'
export const NORMAL_SIGNUP_SUCEESS = 'NORMAL_SIGNUP_SUCEESS'
export const NORMAL_SIGNIN_SUCEESS = 'NORMAL_SIGNIN_SUCEESS'
export const LOGOUT = 'LOGOUT'
export const UPDATE_INFO = 'UPDATE_INFO'

// add products constants..

export const ADD_PRODUCT_IDENTITY_REQUEST = 'ADD_PRODUCT_IDENTITY_REQUEST';
export const ADD_PRODUCT_IDENTITY_SUCCESS = 'ADD_PRODUCT_IDENTITY_SUCCESS';
export const ADD_PRODUCT_DESCRIPTION = 'ADD_PRODUCT_DESCRIPTION'
export const ADD_PRODUCT_DESCRIPTION_SUCCESS = 'ADD_PRODUCT_DESCRIPTION_SUCCESS'
export const ADD_PRODUCT_OPTIONS_AND_PRICES = 'ADD_PRODUCT_OPTIONS_AND_PRICES'
export const ADD_PRODUCT_FILE_UPLOADS = 'ADD_PRODUCT_FILE_UPLOADS'
export const ADD_PRODUCT_OPTIONS_AND_PRICES_SUCCESS = 'ADD_PRODUCT_OPTIONS_AND_PRICES_SUCCESS'
export const ADD_PRODUCT_FILE_OVERVIEW = 'ADD_PRODUCT_FILE_OVERVIEW'
export const ADD_PRODUCT_NEXT_TAB ='ADD_PRODUCT_NEXT_TAB'
export const GO_TO_TAB_STEP= 'GO_TO_TAB_STEP'

// product page 
export const OPEN_PRODUCT_REQUEST_MODAL = 'OPEN_PRODUCT_REQUEST_MODAL'
export const CLOSE_PRODUCT_REQUEST_MODAL = 'CLOSE_PRODUCT_REQUEST_MODAL'

// sharl
export const ADD_ROW = "ADD_ROW"
export const SET_OPTIONS = "SET_OPTIONS"
export const SET_ROWS = "SET_ROW"
export const ADD_MATERIAL = "ADD_MATERIAL"
export const ADD_SIZE = "ADD_SIZE"
export const ADD_INIT_PRICE = "ADD_INIT_PRICE"
export const ADD_OFFER_PRICE = "ADD_OFFER_PRICE"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const ADD_CODE = "ADD_CODE"
export const ADD_OPTION_ID = "ADD_OPTION_ID"
export const DELETE_ROW = "DELETE_ROW"
export const ADD_PRODUCT_PICTURES = "ADD_PRODUCT_PICTURES"
export const OPTIONS_STORED ="OPTIONS_STORED"





// entities and pages loaded data

export const GET_BRAND_DATA = 'GET_BRAND_DATA'